# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privasys < Formula
  desc "Deploy and verify confidential apps from your terminal or your agent"
  homepage "https://privasys.org"
  version "0.24.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Privasys/cli/releases/download/v0.24.0/privasys_0.24.0_darwin_amd64.tar.gz"
      sha256 "15204c0b6537cabf8a2303202a845ad70f14e595cbd90bf780666449a4972e43"

      define_method(:install) do
        bin.install "privasys"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Privasys/cli/releases/download/v0.24.0/privasys_0.24.0_darwin_arm64.tar.gz"
      sha256 "889e41a4e72728922866113b99c25b27661536ea6db5546d424dc39128e24c96"

      define_method(:install) do
        bin.install "privasys"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Privasys/cli/releases/download/v0.24.0/privasys_0.24.0_linux_amd64.tar.gz"
      sha256 "2292e5d6e5f02a9256f9fcf8145c5bdc6b243253862c1aec577616a43842d8cd"
      define_method(:install) do
        bin.install "privasys"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Privasys/cli/releases/download/v0.24.0/privasys_0.24.0_linux_arm64.tar.gz"
      sha256 "0108b102cc31d97904b7cfca305602806431781b3ecf2c2f58fa3990c7f2cd96"
      define_method(:install) do
        bin.install "privasys"
      end
    end
  end

  test do
    system "#{bin}/privasys", "version"
  end
end
